import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { initWorkspace } from '../src/core/init.js';

describe('initWorkspace', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'hpm-test-init-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('scaffolds a complete profile structure with initial sync', () => {
    const result = initWorkspace({
      targetDir: tmpDir,
      profileName: 'agent-1',
      logger: () => {}
    });

    assert.equal(result.profileName, 'agent-1');
    assert.equal(result.createdFiles.length, 5);

    // Common files
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'common', 'config.yaml')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'common', 'SOUL.md')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'common', 'skills')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'common', 'plugins')));

    // Agent custom files
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'agent-1', 'config.custom.yaml')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'agent-1', 'SOUL.custom.md')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'agent-1', 'cron', 'jobs.custom.json')));

    // Compiled files generated by initial sync
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'agent-1', 'config.yaml')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'agent-1', 'SOUL.md')));
    assert.ok(fs.existsSync(path.join(tmpDir, 'profiles', 'agent-1', 'cron', 'jobs.json')));
  });

  it('does not overwrite existing files unless force is specified', () => {
    initWorkspace({
      targetDir: tmpDir,
      profileName: 'main',
      logger: () => {}
    });

    const customConfig = path.join(tmpDir, 'profiles', 'main', 'config.custom.yaml');
    fs.writeFileSync(customConfig, '# Custom user edits\nfoo: bar\n');

    // Run init again without force
    const secondResult = initWorkspace({
      targetDir: tmpDir,
      profileName: 'main',
      logger: () => {}
    });

    assert.equal(secondResult.createdFiles.length, 0);
    assert.equal(secondResult.skippedFiles.length, 5);
    assert.ok(fs.readFileSync(customConfig, 'utf8').includes('foo: bar'));

    // Run init with force
    const thirdResult = initWorkspace({
      targetDir: tmpDir,
      profileName: 'main',
      force: true,
      logger: () => {}
    });

    assert.equal(thirdResult.createdFiles.length, 5);
  });
});
